---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: falco-ui-credentials
  namespace: falco
spec:
  encryptedData:
    password: AgBOK8KfhijC3oh+abqKtLor8QTfy0gYT3kqlebrb6n1LoXa7jwZMrHQ9e1dZi+X+IrHhDrj3LS64MFnsT5s2Em8GbTaEREoHnlAcCeiic4C7jxIsTDpelZm30wUxWM4Ct1UoAT23Cy77Pnlp4G8NwwReudOTQRsenFPqnfJ11DcpAR9CEYSW/hjw+nHC92rJJw/BVqBfGMLh43RfQdefFE0e1D01IxuselJ4rb/K7yVKvLMZxOlnZLWpb6tj28T0XpLt2HyjIRq3fdyN4ASo8Sr1/TK+8hoxVpxl4h0+8VuWQlPv4fR+BVgGWCS3Eudv2yUw/UDMBCbpwL8ZqQmoKOBm7e/gLmL33GjgVhtQJey1E3g6rbRQax7d1ogpT/oqxvL9YcA+ZKy0iixtog1kkroz2vIuZVqJAemLl+WQzvoOgy+20wWxXpxiwB090Ncb6s75Zjuu1IZ0y+gQW58PmqZLjyGglEqWs1E+aeHtjcVZ6qK4HIIc73K3hZXX8I5SqshjOXD2gBqTwUTABqgDTrNbXHwo3fN3AgD1hxidAxm/D9wP0y9ugMHSzs5UG2ZL2JaQ25BCJlBLR1oj0LalD2kdmh8peh89APhOBDEZPVIKD46PVFpy3GLWj9D3bm83UD7tciPaAELmY0cUQvGX/ryFa8H+5jwnKi6l5XXn2/C42qnr2n67eEDnUok3n3RtTWIWLPyR9aUuWX7nXswk+EehBcCFJINRw==
    username: AgAJOfsW3tCEkVXjcFPbjdumhieVRFkwOx9P0kQLP32k8slZ9eZGDdVL6nKck4xQeRSTmIPbZ7XZAtPsnI9DW9N9JtYve/i6Ao1L28nOCqRsUPF4F5L1eXSRBjynSbXqBBtHAm0E/KPDi+a1+RP2e42PbhR1q+V510gwBlKF/qcoblxsOI9bHtFkhjXbU3jOHVhFMuBdSAFCKWODaXq07p6rDkxwV2q0y3ZFc43TMCR5MjaiQ3rPId4b8d24KtnB4keUH4tH/UYh5FTDYJUFNkktNBckmsb0tNN/vC4+tjGYixvNwZslC91ALrw/K9r3t2HqvM79MCPVvsj7AGh3DQooIKArTp5nUOt5n99r/txXvzpBcN2r9/awNAiRLkbydTX8bZKLzLCf8jH4Wxi/lZbYw2TzzrBKibOf+DzyeK5Sk430wgUUYGDPE/tAaBcH+hPvDhiFSxcLG9lyG3lZ6W/7zKXh49jqCdShpv68O7VsBprE4D5j65c7g554OvOqUyt8YA52Z5xLq/f6sZ3Aqu+WdlIx45bN7Pq8iIaRXHZbg0RV5KkGCsqPRhHfiUXzUx5HO8wwt8oxBLIHszOWv6FG/q0OEFflg8bEgEG773N0NuVqJXkD7yLsgzE91ZrHdYTWGTxXhIGjJsPcNv+x8KaE01k1WWHdrAX+Cdez9fYmKNDoo6OlyCglCvaW+fJA9Yb+zJHK7A==
  template:
    metadata:
      creationTimestamp: null
      name: falco-ui-credentials
      namespace: falco
