---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: falco-ui-credentials
  namespace: falco
spec:
  encryptedData:
    user: AgC/SAHu91+9ASs87FNV2vwAiQFp0CrpbUsQqxF5wANpIxHTex6i+pV46ucu5Ic88s/Ak2954WjOnoeYwa+h4ZGVgR7a/qbdGg00d6UNY8BzaUyiHnO8+7oak0Hljk2cj6d2svFqkYPHl4NPZki7KUv1rQl4zK95cJHMatDMeK55Yrwi2pYYMdscvOqxLZWhDFn4Z4YnLPzD5esNZTpyA6C+RsGyX+V0CnrCgccjzPw8wotnIpPmpYPUGlxyjlG4lu3z8EenW6KHFFNwaBJbHIwKWd6Xv7vCIk/mgMoUomb46KqPdeHBKgay/EE2kJTA4Fob7EAgmkkGBvoqoy12UDCx/umYL0z5CJNrktfYd3c/fXJtYMqpIEy1F8gL75LojR2yCUyfCeJhumfsSFYJMvYL4SlHglnpg/FO92KaNRRWkxxOsLWM+vFhM9qdQxORWdLhubbim91O2MsQW6LNncT5ZnNoEa9C9ILm6QH7morpWDbvxsaOueQXvKn16I/y81NvKghullpK8hGu1doxy9YNC+czWEp21m9wgmcA0G46VYB6qf67BGK9AbEviTfDGTqX1d19HMxjaIpB/O38a54cHAkpQ+nPkSUlhEKRquZbHILuW+XAq9zDwCK6bALiTk0UBlo7UZVdokNYA63TMWjGS1H0N1RPdkSg+fUQoyTkN1pwnNYv7hHAMaRkVlA8pygE3uTut2808JPUJSkU/sz3UERaizsUn1I5IrskRw==
  template:
    metadata:
      creationTimestamp: null
      name: falco-ui-credentials
      namespace: falco
