---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBmrQnyYV9SQ/y/Y7N449w0vL7SFh0OUEQ5m32ZWXKUP3ebQMTg0BCd1rUI4A942zXJGYIyTcGybErmLa43P7lk9fo7BF2lY7vpiq4KwvHCqXPGHLV7elCsok6WcVBON838m46/8mQljRCpOGsGcQgYwKDk/54CmXeIcT0pk+K7fX9bHiT3WLZILf9L9WpCGPHUjanemGoecNDSUlHcempyfcdVYy5wdvbwZXdgFy7bLOfD5NE6Cj2p2+5RpNcH9vLTem8r0tkFLHCMfes0ThkrYKCUKKY2lNk3Gk9bkMWo4R2pQMFc2iNuBcFhUlXMJXj85IiT4NNEkXbP43zNpQXPduuZJz65VMmhuxA2/OGtb8ztPT0/lqWnx8rVNcNJlT/lH7wRxgVE5nq41ba3mcVrGmyKVFVIRfwD5sKVC2Rn6S0khUllHcblPtxeMc51LVeAkWujaQbm5T6i4115yYTKYtMN3hxDjDfO4IAQefQt4w2XK6kivthE7ul8mG3FH8BarXlWDCLniKqlv82ZGTfHAdzwddI2hNBXHAtHHuRKHk8U4FHyKeD4MHBHOloT5u0AUnbKS+3Xmxfb7VmyJv4Gh7/uf6Zd5cCvcRmomgeDfpkjMiwVGXLf3UKQLk30jX6Td85x0Qpwk7jiiz5HgHrslfcezozVxHUBMeGCSqAP0BP55AOcJYkyQitJP9kSMyAzFzRZpiCEL6U2ONvCiqO0XH6NKis=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring
