---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCjJhpHcBlv4tctpiz+Hg429JW5PhTQFy1l6hu4SxivnYi/kX6mThXhHgfTFSmOdJUveesR1dma7SrIfjN59WWuTmEBCOQAhKpd7TRMcN9RYk47jW+eV2gRsRNPuARyJWnDlrhKloudwnbHHeOjuvIMWqsb9Jnd7Hfda14DpXk5x+v20zEak5ogk9kUPuLORYUWlxD4KBVRlJK+9pVQ7zFL2soNPvyLKZCRakmZ8cNqHdU94pHuTI5MbpYzsPI9KdnFnMdvhhPBAsPww+Q5RqwfZeNu+GJvmwVnTTblah9d01jf07cP6f0IML3vvY3nr4RgANTJ6sW8nwDSh4LqStVDbg+a/hKZbZq/kcSnFgyXxYEn+XuZhU2WOddAJLFxLd4buDjZGc2qhg1xxsLw594Xv2K7Du3XNIks6bkcMeqVgci/gpp4iJ8r7UbW63LfPyvsP2gDu2wjsYWm1UQG88C0V8BMJFCuQCnfuNp2XQwTU9qulrhKmxqtVAoprFGrhb5yprr/jU3ePTAMEikM/fOQ1JlXTXxRrEb28uvNFIYNlremsgOM1OTpXBcBYRi1ep52vz3epDGwN09HQrUh+HXkvszIRAgUjuq5F2xxYUU0z4fyws6j4iSXk3FCGSRXtdy1vA8FOlY55yKwEx6an6eHCfQdZUpMem9Rwu0rA3rm05/uf2V1rVYY1ihTBiCHRw1ENkWL1a3sOViFtNmthLmYeN/EvKw=
    admin-user: AgB2L/u50td0YESMJADN6sGz3jbGLktisJPzR3wbw57FJCdz51m/Z9m0UAvZm1/kvl56QqhEd++1VN59+WqkZzBGIAGTA4uBkJV5vwO31dEBsZWvMRV9ue0YlVweUlzFybN/YzEWYxesgKmvrKFnfSbaYhtWhFUzavQ0BdwwAUou7qE3A2argYkW+ccWL7CjvI5pPGPEOg8SzF/KBTIIzyt/vzAa9e8hhi3lOSlvigpvXx48vzIYj4q1BQif3zQ1n92g4pvP4kK3GFF2BsilyI3xUyy9hMLebo7DJ3rRKZFBxhj53pwrp98JU2HZJCHGjGBBGE1eZhuu1e7rxvA5P1HNfjJsUWWOJI+TOGM7/oAe0VgPD7epuDffgl9e9Ts9PANCQq0CoVir9venc+x2TxYk2OtWDs7hSXfgBJU6QbsaGsUKJdUlFi1AvNHWAq7XjmW/NTxLUDZQz+dYiaLEErxIeEh5WTVE22VdCjkPeFkqzw1FmwyNVAjX1OGSB44YZTlwbNNkBkymOsA1o0H5oDmxpkx9EbtKQ/r1VF77CdJng8os8zZ+gTCkYNiAdBUqDCav1Bo1Mz0SmSH/EHpMg0KlJp+/pJ38QBmBUoKtsCH8AnE0mnoiNiM9N3dTkRQTluFbRfsp2a60x/EvjYVJsRMN8YW8Kq9JKeqbb9CQiDNn8MF+Xu5Jk5GnArPCwcpyU0KYywzLBA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring
