server:
  service:
    type: ClusterIP

  persistentVolume:
    enabled: true
    size: 5Gi

alertmanager:
  enabled: false

pushgateway:
  enabled: false 

extraScrapeConfigs: |
    - job_name: proxmox-host
      static_configs:
        - targets:
            - 192.168.1.5:9100
          labels:
            instance: proxmox
